# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_date',
            field=models.DateField(editable=False),
        ),
    ]
