# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 18:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_auto_20160612_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(2, message='el monto no puede ser inferior a $1')], verbose_name='Donacion'),
        ),
    ]
