# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_auto_20160612_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
