# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 16:16
from __future__ import unicode_literals
import datetime

from django.db import migrations

from django.contrib.auth.models import User

from app.donation.models import Donation

def seed_donations(apps, schema_editor):
#    users = User.objects.all().exclude(username='admin')
    juan = User.objects.get(username='juan88')
    mica = User.objects.get(username='micaela_sk8')
    donation = apps.get_model('donation', 'Donation')
    d1 = donation(amount=50)
    d1.user_id = juan.id
    d1.save()
    d1.donation_date=datetime.date(2016,7,1)
    d1.save()
    d2 = donation(amount=100 )
    d2.user_id = mica.id
    d2.save()
    d2.donation_date=datetime.date(2016,6,1)
    d2.save()
    d3 = donation(amount=75)
    d3.user_id = juan.id
    d3.save()
    d3.donation_date=datetime.date(2016,6,30)
    d3.save()
    d4 = donation(amount=50)
    d4.user_id = mica.id
    d4.save()
    d4.donation_date=datetime.date(2016,7,8)
    d4.save()
    d5 = donation(amount=10)
    d5.user_id = juan.id
    d5.save()
    d5.donation_date=datetime.date(2016,3,1)
    d5.save()
    # por tener donaciones los usuarios deben ser premium
    juan.couchinnuser.premium = True
    juan.save()
    mica.couchinnuser.premium = True
    mica.save()
    
class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_auto_20160623_1922'),
        ('session', '0008_auto_20160707_2258'),
    ]

    operations = [
        migrations.RunPython(seed_donations),
    ]
