# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 23:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couchinnuser',
            old_name='valoracion_como_anfitrion',
            new_name='as_host_rank',
        ),
        migrations.RenameField(
            model_name='couchinnuser',
            old_name='valoracion_como_inquilino',
            new_name='as_tenant_rank',
        ),
        migrations.RenameField(
            model_name='couchinnuser',
            old_name='donaciones',
            new_name='donations',
        ),
    ]
