# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_auto_20160602_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couchinnuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1),
        ),
    ]
