# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_auto_20160603_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couchinnuser',
            name='donations',
        ),
        migrations.AddField(
            model_name='couchinnuser',
            name='premium',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='couchinnuser',
            name='total_donations',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
