# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_auto_20160612_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='couchinnuser',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='session'),
        ),
    ]
