# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_auto_20160614_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couchinnuser',
            name='gender',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10),
        ),
    ]
