# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 22:58
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import User, UserManager

from django_countries.fields import Country

from app.session.models import CouchinnUser



def add_superuser(apps, schema_editor):
    # creates a base superuser
    cu = apps.get_model('session', 'CouchinnUser')
    su = User(username='admin', email='admin@admin.com')
    su.set_password('pass12345')
    su.is_superuser = True,
    su.is_staff = True,
    su.save()
    profile = cu()
    profile.user_id = su.id
    profile.save()

    
## users Data
users_data = [
    #user 1
    { 'username': 'juan88',
      'first_name':'Juan Martin',
      'last_name' : 'Rodriguez',
      'email' : 'juan88@gmail.com'},
    #user 2
    { 'username': 'micaela_sk8',
      'first_name':'Micaela',
      'last_name' : 'Gomez',
      'email' : 'micaela_sk8@gmail.com'},
    #user 3
    { 'username': 'pedro',
      'first_name':'Pedro Homero',
      'last_name' : 'Schbaun',
      'email' : 'pedro@gmail.com'}
    ]


# profiles data
couchinnuser_data = [
    # user 1 profile
    {'telephone' : '12345678',
     'nationality': Country('AR'),
     'gender' : 'Masculino'
     },
    #user 2 profile
    {'telephone' : '12345678',
     'nationality': Country('AR'),
     'gender' : 'Femenino'
     },
    #user 3 profile
    {'telephone' : '12345678',
     'nationality': Country('AR'),
     'gender' : 'Masculino'
     }
]
          

def add_app_users(apps, schema_editor):
    ### creates 3 app users with their current profile
    cu = apps.get_model('session', 'CouchinnUser')
    for user, profile in zip(users_data, couchinnuser_data):
        #creates the user and stores in db
        u = User(**user)
        u.set_password('pass12345')
        u.save()
        # creates the profile and relates tu user
        p = cu(**profile)
        p.user_id = u.id
        p.save()
        
         

class Migration(migrations.Migration):

    dependencies = [
        ('session', '0007_auto_20160614_0446'),
    ]

    operations = [
        migrations.RunPython(add_superuser),
        migrations.RunPython(add_app_users)
    ]
