# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lodgment', '0014_remove_place_gallery'),
        ('gallery', '0002_auto_20160607_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='gallery',
        ),
        migrations.AddField(
            model_name='photo',
            name='place',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lodgment.Place'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(default='untitled', max_length=20, verbose_name='titulo'),
        ),
    ]
