# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20160607_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(editable=False, upload_to='places'),
        ),
    ]
