# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20160607_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='places'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='place',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='lodgment.Place'),
        ),
    ]
