# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 04:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20160607_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='place',
        ),
        migrations.AddField(
            model_name='photo',
            name='gallery',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to='gallery.Gallery'),
        ),
    ]
