# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 21:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodgment', '0004_auto_20160531_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lodgment',
            name='reservations_available',
        ),
        migrations.RemoveField(
            model_name='lodgment',
            name='reservations_taken',
        ),
        migrations.AddField(
            model_name='category',
            name='reservations_available',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de personas'),
            preserve_default=False,
        ),
    ]
