# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lodgment', '0005_auto_20160601_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
