# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 00:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodgment', '0006_auto_20160601_2256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lodgment',
            options={'verbose_name': 'Hospedaje', 'verbose_name_plural': 'Hospedajes'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Solicitud', 'verbose_name_plural': 'Solicitudes'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Resenia', 'verbose_name_plural': 'Resenias'},
        ),
    ]
