# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodgment', '0008_auto_20160602_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Lugar', 'verbose_name_plural': 'Lugares'},
        ),
    ]
