# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodgment', '0010_auto_20160602_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodgment',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
