# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodgment', '0011_lodgment_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='state',
            field=models.CharField(choices=[('PE', 'pending'), ('RJ', 'rejected'), ('AC', 'acepted')], default='PE', max_length=2),
        ),
    ]
