# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('lodgment', '0012_auto_20160603_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Inmueble', 'verbose_name_plural': 'Inmuebles'},
        ),
        migrations.AddField(
            model_name='lodgment',
            name='title',
            field=models.CharField(default='sin titulo', max_length=50, verbose_name='Titulo'),
        ),
        migrations.AddField(
            model_name='place',
            name='gallery',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gallery.Gallery'),
        ),
    ]
