# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodgment', '0013_auto_20160607_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='gallery',
        ),
    ]
