# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 04:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20160608_0457'),
        ('lodgment', '0014_remove_place_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='gallery',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to='gallery.Gallery'),
        ),
        migrations.AlterField(
            model_name='place',
            name='user',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
