# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodgment', '0015_auto_20160608_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
