# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 05:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lodgment', '0016_place_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgment',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodgment.Place', verbose_name='Inmueble'),
        ),
        migrations.AlterField(
            model_name='lodgment',
            name='reservations_available',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de personas'),
        ),
        migrations.AlterField(
            model_name='place',
            name='deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
