# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodgment', '0017_auto_20160612_0509'),
        ('lodgment', '0012_auto_20160612_1943'),
    ]

    operations = [
    ]
