# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 19:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodgment', '0018_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='direction',
            field=models.TextField(max_length=100, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='place',
            name='score',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Valoracion'),
        ),
    ]
