# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 05:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20160623_1922'),
        ('lodgment', '0019_auto_20160623_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'couch', 'verbose_name_plural': 'couches'},
        ),
        migrations.RenameField(
            model_name='place',
            old_name='direction',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='lodgment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='lodgment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='lodgment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lodgment',
            name='title',
        ),
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.TextField(default=None, max_length=500, verbose_name='Descripci\xf3n'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='guests',
            field=models.IntegerField(default=0, verbose_name='Huespedes'),
        ),
        migrations.AlterField(
            model_name='lodgment',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodgment.Place', verbose_name='couch'),
        ),
        migrations.AlterField(
            model_name='lodgment',
            name='reservations_available',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de huespedes'),
        ),
    ]
