# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 23:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodgment', '0020_auto_20160703_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='name',
        ),
    ]
