# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 06:07
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0007_auto_20160623_1922'),
        ('gallery', '0007_auto_20160609_1922'),
        ('lodgment', '0020_auto_20160628_0517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Couch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Nombre')),
                ('description', models.TextField(max_length=500, verbose_name='Descripci\xf3n')),
                ('address', models.TextField(max_length=100, verbose_name='Direccion')),
                ('city', models.TextField(max_length=100, verbose_name='Ciudad')),
                ('province', models.TextField(max_length=100, verbose_name='Provincia')),
                ('score', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Valoracion')),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('guests', models.IntegerField(default=0, verbose_name='Huespedes')),
                ('initial_date', models.DateField(verbose_name='Fecha de inicio')),
                ('finish_date', models.DateField(verbose_name='Fecha de fin')),
                ('reservations_available', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de huespedes')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Category')),
                ('gallery', models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to='gallery.Gallery')),
                ('user', models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'couch',
                'verbose_name_plural': 'couches',
            },
        ),
        migrations.RemoveField(
            model_name='lodgment',
            name='place',
        ),
        migrations.RemoveField(
            model_name='place',
            name='category',
        ),
        migrations.RemoveField(
            model_name='place',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='place',
            name='user',
        ),
        migrations.RemoveField(
            model_name='request',
            name='lodgment',
        ),
        migrations.RemoveField(
            model_name='review',
            name='lodgment',
        ),
        migrations.DeleteModel(
            name='Lodgment',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.AddField(
            model_name='request',
            name='couch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lodgment.Couch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='Couch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lodgment.Couch'),
            preserve_default=False,
        ),
    ]
