# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodgment', '0022_request_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_score',
            field=models.BooleanField(default=False),
        ),
    ]
