# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 03:21
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import User
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('lodgment', '0023_request_is_score'),
        ('session', '0008_auto_20160707_2258'),
        ('backend', '0008_auto_20160707_2248'),
        ('gallery', '0007_auto_20160609_1922'),
        
    ]

    def populate_places(apps, schema_editor):
        cat = apps.get_model('backend', 'Category')
        place = apps.get_model('lodgment', 'Place')
        gallery = apps.get_model('gallery', 'Gallery')
        
        aplace = place()
        aplace.title = 'casa en la playa'
        aplace.direction = '119 #246'
        aplace.city = 'La Plata'
        aplace.province = 'buenos aires'
        aplace.description = 'un couchin creado'
        aplace.initial_date = datetime.date(2016,6,1)
        aplace.finish_date = datetime.date(2016,6,15)
        aplace.reservations_available = 3

        gal = gallery()
        gal.save()
        aplace.gallery = gal
        aplace.category = cat.objects.order_by('?').first()
        aplace.user_id = User.objects.get(username='juan88').id
        aplace.save()

        
    operations = [ migrations.RunPython(populate_places)
    ]
