# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 04:23
from __future__ import unicode_literals

import datetime

from django.db import migrations
from django.contrib.auth.models import User

class Migration(migrations.Migration):

    dependencies = [
        ('lodgment', '0024_auto_20160715_0321'),
        
    ]

    def create_and_attach_request(app, schema_editor):
        rq = app.get_model('lodgment', 'Request')
        co = app.get_model('lodgment', 'Place')
        couchin = co.objects.get(title='casa en la playa')
        # pedido de usuario pedro al couch de juan88
        req_user = User.objects.get(username='pedro')

        req = rq()
        req.initial_date = datetime.date(2016,6,1)
        req.finish_date = datetime.date(2016,6,8)
        req.state = 'AC'

        req.author_id = req_user.id
        req.couch_id = couchin.id
        
        req.save()
        # un pedido de micaela_sk8 en otras fechas al mismo couch
        req_user = User.objects.get(username='micaela_sk8')

        req = rq()
        req.initial_date = datetime.date(2016,6,10)
        req.finish_date = datetime.date(2016,6,14)
        req.state = 'AC'

        req.author_id = req_user.id
        req.couch_id = couchin.id
        
        req.save()
    operations = [
        migrations.RunPython(create_and_attach_request)
    ]
