# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 06:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodgment', '0025_auto_20160715_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Valoraci\xf3n'),
        ),
    ]
