# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 12:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lodgment', '0028_auto_20160715_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date_accepted',
            field=models.DateField(default=datetime.datetime(2016, 7, 15, 12, 55, 22, 934066, tzinfo=utc), verbose_name='fecha de aceptacion'),
            preserve_default=False,
        ),
    ]
