# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 12:55
from __future__ import unicode_literals

from django.db import migrations

import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('lodgment', '0029_request_date_accepted'),
    ]

    def repopulate_date_accepted(app, schema_editor):
        req = app.get_model('lodgment', 'Request')

        r = req.objects.get(author__username='pedro')
        r.date_accepted = datetime.date(2016,5,3)
        r.save()

        r = req.objects.get(author__username='micaela_sk8')
        r.date_accepted = datetime.date(2016,5,22)
        r.save()

        
    operations = [ migrations.RunPython(repopulate_date_accepted)
    ]
