# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 21:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_office', models.CharField(max_length=50, verbose_name='Nombre:')),
            ],
        ),
        migrations.CreateModel(
            name='Lodgment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('initial_date', models.DateTimeField()),
                ('finish_date', models.DateTimeField()),
                ('reservations_taken', models.IntegerField(default=0)),
                ('reservations_available', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de personas')),
                ('score', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Valoracion')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodgment.Category')),
            ],
        ),
    ]
