# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodgment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgment',
            name='finish_date',
            field=models.DateField(verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='lodgment',
            name='initial_date',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
    ]
