# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodgment', '0002_auto_20160530_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_office',
            new_name='name',
        ),
    ]
