# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 22:38
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lodgment', '0003_auto_20160530_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('initial_date', models.DateField(verbose_name='Fecha de inicio')),
                ('finish_date', models.DateField(verbose_name='Fecha de fin')),
                ('state', models.CharField(choices=[('PE', 'en espera'), ('RJ', 'rechazado'), ('AC', 'aceptado')], default='PE', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Resenia')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Valoracion')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lodgment',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='lodgment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodgment.Lodgment'),
        ),
        migrations.AddField(
            model_name='request',
            name='lodgment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodgment.Lodgment'),
        ),
    ]
