# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lodgment', '0021_remove_place_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=250, verbose_name='Pregunta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('couch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodgment.Place')),
            ],
        ),
    ]
