# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-09 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_question_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='body',
            field=models.CharField(max_length=500, verbose_name='Pregunta'),
        ),
    ]
