# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='body',
            field=models.CharField(blank=True, max_length=500, verbose_name='Respuesta'),
        ),
    ]
