# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 22:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre:')),
                ('reservations_available', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de personas')),
            ],
        ),
    ]
