# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20160602_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='reservations_available',
        ),
    ]
