# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 22:48
from __future__ import unicode_literals

from django.db import migrations

categories = [
    'Sillon',
    'Cama',
    'Cama king Size',
    'Cuarto',
    'Departamento',
    'Casa',
    'Casa Quinta'
]

def populate_categories(apps, schema_editor):
    Category = apps.get_model('backend', 'Category')
    for category in categories:
        c = Category(name=category)
        c.save()
        

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20160623_1922'),
    ]

    operations = [ migrations.RunPython(populate_categories)
    ]
